// African countries in Natural Earth / world-atlas, keyed by ISO 3166-1 numeric id.
// `code` is the ISO alpha-2 code used for the flag file in public/flags/<code>.svg.
// Somaliland has no ISO id in Natural Earth and is shown with Somalia's flag.
// Western Sahara (disputed) is shown without a flag.
export const africanCountries: Record<string, { code: string | null; name: string }> = {
  "012": { code: "dz", name: "Algeria" },
  "024": { code: "ao", name: "Angola" },
  "204": { code: "bj", name: "Benin" },
  "072": { code: "bw", name: "Botswana" },
  "854": { code: "bf", name: "Burkina Faso" },
  "108": { code: "bi", name: "Burundi" },
  "132": { code: "cv", name: "Cabo Verde" },
  "120": { code: "cm", name: "Cameroon" },
  "140": { code: "cf", name: "Central African Republic" },
  "148": { code: "td", name: "Chad" },
  "174": { code: "km", name: "Comoros" },
  "178": { code: "cg", name: "Congo" },
  "180": { code: "cd", name: "Democratic Republic of the Congo" },
  "384": { code: "ci", name: "Côte d'Ivoire" },
  "262": { code: "dj", name: "Djibouti" },
  "818": { code: "eg", name: "Egypt" },
  "226": { code: "gq", name: "Equatorial Guinea" },
  "232": { code: "er", name: "Eritrea" },
  "748": { code: "sz", name: "Eswatini" },
  "231": { code: "et", name: "Ethiopia" },
  "266": { code: "ga", name: "Gabon" },
  "270": { code: "gm", name: "Gambia" },
  "288": { code: "gh", name: "Ghana" },
  "324": { code: "gn", name: "Guinea" },
  "624": { code: "gw", name: "Guinea-Bissau" },
  "404": { code: "ke", name: "Kenya" },
  "426": { code: "ls", name: "Lesotho" },
  "430": { code: "lr", name: "Liberia" },
  "434": { code: "ly", name: "Libya" },
  "450": { code: "mg", name: "Madagascar" },
  "454": { code: "mw", name: "Malawi" },
  "466": { code: "ml", name: "Mali" },
  "478": { code: "mr", name: "Mauritania" },
  "480": { code: "mu", name: "Mauritius" },
  "504": { code: "ma", name: "Morocco" },
  "508": { code: "mz", name: "Mozambique" },
  "516": { code: "na", name: "Namibia" },
  "562": { code: "ne", name: "Niger" },
  "566": { code: "ng", name: "Nigeria" },
  "646": { code: "rw", name: "Rwanda" },
  "678": { code: "st", name: "São Tomé and Príncipe" },
  "686": { code: "sn", name: "Senegal" },
  "690": { code: "sc", name: "Seychelles" },
  "694": { code: "sl", name: "Sierra Leone" },
  "706": { code: "so", name: "Somalia" },
  "710": { code: "za", name: "South Africa" },
  "728": { code: "ss", name: "South Sudan" },
  "729": { code: "sd", name: "Sudan" },
  "834": { code: "tz", name: "Tanzania" },
  "768": { code: "tg", name: "Togo" },
  "788": { code: "tn", name: "Tunisia" },
  "800": { code: "ug", name: "Uganda" },
  "894": { code: "zm", name: "Zambia" },
  "716": { code: "zw", name: "Zimbabwe" },
  "732": { code: null, name: "Western Sahara" },
};

/** Natural Earth features without an ISO id that belong on the Africa map. */
export const unnumberedAfrica: Record<string, { code: string; name: string }> = {
  Somaliland: { code: "so", name: "Somalia" },
};
