import dimensions from "./photo-dimensions.json";

// Web-ready photos generated by `npm run images` (see scripts/optimize-images.mjs).
export type PhotoName = keyof typeof dimensions;

export const photoSrc = (name: PhotoName) =>
  name === "environmental" ? "/images/environmental.svg" : `/images/${name}.webp`;

export const photoSize = (name: PhotoName) => dimensions[name];
